In [ ]:
from google.colab import files
files.upload()

Saving train (1).csv to train (1).csv

{'train (1).csv': b'PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked\r\n1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S\r\n2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C\r\n3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S\r\n4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S\r\n5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S\r\n6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q\r\n7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S\r\n8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,,S\r\n9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,,S\r\n10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,,C\r\n11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S\r\n12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S\r\n13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,,S\r\n14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,,S\r\n15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,,S\r\n16,1,2,"Hewlett, Mrs. (Mary D Kingcome) ",female,55,0,0,248706,16,,S\r\n17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,,Q\r\n18,1,2,"Williams, Mr. Charles Eugene",male,,0,0,244373,13,,S\r\n19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31,1,0,345763,18,,S\r\n20,1,3,"Masselmani, Mrs. Fatima",female,,0,0,2649,7.225,,C\r\n21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26,,S\r\n22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13,D56,S\r\n23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,,Q\r\n24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S\r\n25,0,3,"Palsson, Miss. Torborg Danira",female,8,3,1,349909,21.075,,S\r\n26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38,1,5,347077,31.3875,,S\r\n27,0,3,"Emir, Mr. Farred Chehab",male,,0,0,2631,7.225,,C\r\n28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263,C23 C25 C27,S\r\n29,1,3,"O\'Dwyer, Miss. Ellen ""Nellie""",female,,0,0,330959,7.8792,,Q\r\n30,0,3,"Todoroff, Mr. Lalio",male,,0,0,349216,7.8958,,S\r\n31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,,C\r\n32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,,1,0,PC 17569,146.5208,B78,C\r\n33,1,3,"Glynn, Miss. Mary Agatha",female,,0,0,335677,7.75,,Q\r\n34,0,2,"Wheadon, Mr. Edward H",male,66,0,0,C.A. 24579,10.5,,S\r\n35,0,1,"Meyer, Mr. Edgar Joseph",male,28,1,0,PC 17604,82.1708,,C\r\n36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52,,S\r\n37,1,3,"Mamee, Mr. Hanna",male,,0,0,2677,7.2292,,C\r\n38,0,3,"Cann, Mr. Ernest Charles",male,21,0,0,A./5. 2152,8.05,,S\r\n39,0,3,"Vander Planke, Miss. Augusta Maria",female,18,2,0,345764,18,,S\r\n40,1,3,"Nicola-Yarred, Miss. Jamila",female,14,1,0,2651,11.2417,,C\r\n41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40,1,0,7546,9.475,,S\r\n42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27,1,0,11668,21,,S\r\n43,0,3,"Kraeff, Mr. Theodor",male,,0,0,349253,7.8958,,C\r\n44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3,1,2,SC/Paris 2123,41.5792,,C\r\n45,1,3,"Devaney, Miss. Margaret Delia",female,19,0,0,330958,7.8792,,Q\r\n46,0,3,"Rogers, Mr. William John",male,,0,0,S.C./A.4. 23567,8.05,,S\r\n47,0,3,"Lennon, Mr. Denis",male,,1,0,370371,15.5,,Q\r\n48,1,3,"O\'Driscoll, Miss. Bridget",female,,0,0,14311,7.75,,Q\r\n49,0,3,"Samaan, Mr. Youssef",male,,2,0,2662,21.6792,,C\r\n50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18,1,0,349237,17.8,,S\r\n51,0,3,"Panula, Master. Juha Niilo",male,7,4,1,3101295,39.6875,,S\r\n52,0,3,"Nosworthy, Mr. Richard Cater",male,21,0,0,A/4. 39886,7.8,,S\r\n53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49,1,0,PC 17572,76.7292,D33,C\r\n54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29,1,0,2926,26,,S\r\n55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65,0,1,113509,61.9792,B30,C\r\n56,1,1,"Woolner, Mr. Hugh",male,,0,0,19947,35.5,C52,S\r\n57,1,2,"Rugg, Miss. Emily",female,21,0,0,C.A. 31026,10.5,,S\r\n58,0,3,"Novel, Mr. Mansouer",male,28.5,0,0,2697,7.2292,,C\r\n59,1,2,"West, Miss. Constance Mirium",female,5,1,2,C.A. 34651,27.75,,S\r\n60,0,3,"Goodwin, Master. William Frederick",male,11,5,2,CA 2144,46.9,,S\r\n61,0,3,"Sirayanian, Mr. Orsen",male,22,0,0,2669,7.2292,,C\r\n62,1,1,"Icard, Miss. Amelie",female,38,0,0,113572,80,B28,\r\n63,0,1,"Harris, Mr. Henry Birkhardt",male,45,1,0,36973,83.475,C83,S\r\n64,0,3,"Skoog, Master. Harald",male,4,3,2,347088,27.9,,S\r\n65,0,1,"Stewart, Mr. Albert A",male,,0,0,PC 17605,27.7208,,C\r\n66,1,3,"Moubarek, Master. Gerios",male,,1,1,2661,15.2458,,C\r\n67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29,0,0,C.A. 29395,10.5,F33,S\r\n68,0,3,"Crease, Mr. Ernest James",male,19,0,0,S.P. 3464,8.1583,,S\r\n69,1,3,"Andersson, Miss. Erna Alexandra",female,17,4,2,3101281,7.925,,S\r\n70,0,3,"Kink, Mr. Vincenz",male,26,2,0,315151,8.6625,,S\r\n71,0,2,"Jenkin, Mr. Stephen Curnow",male,32,0,0,C.A. 33111,10.5,,S\r\n72,0,3,"Goodwin, Miss. Lillian Amy",female,16,5,2,CA 2144,46.9,,S\r\n73,0,2,"Hood, Mr. Ambrose Jr",male,21,0,0,S.O.C. 14879,73.5,,S\r\n74,0,3,"Chronopoulos, Mr. Apostolos",male,26,1,0,2680,14.4542,,C\r\n75,1,3,"Bing, Mr. Lee",male,32,0,0,1601,56.4958,,S\r\n76,0,3,"Moen, Mr. Sigurd Hansen",male,25,0,0,348123,7.65,F G73,S\r\n77,0,3,"Staneff, Mr. Ivan",male,,0,0,349208,7.8958,,S\r\n78,0,3,"Moutal, Mr. Rahamin Haim",male,,0,0,374746,8.05,,S\r\n79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29,,S\r\n80,1,3,"Dowdell, Miss. Elizabeth",female,30,0,0,364516,12.475,,S\r\n81,0,3,"Waelens, Mr. Achille",male,22,0,0,345767,9,,S\r\n82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29,0,0,345779,9.5,,S\r\n83,1,3,"McDermott, Miss. Brigdet Delia",female,,0,0,330932,7.7875,,Q\r\n84,0,1,"Carrau, Mr. Francisco M",male,28,0,0,113059,47.1,,S\r\n85,1,2,"Ilett, Miss. Bertha",female,17,0,0,SO/C 14885,10.5,,S\r\n86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33,3,0,3101278,15.85,,S\r\n87,0,3,"Ford, Mr. William Neal",male,16,1,3,W./C. 6608,34.375,,S\r\n88,0,3,"Slocovski, Mr. Selman Francis",male,,0,0,SOTON/OQ 392086,8.05,,S\r\n89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263,C23 C25 C27,S\r\n90,0,3,"Celotti, Mr. Francesco",male,24,0,0,343275,8.05,,S\r\n91,0,3,"Christmann, Mr. Emil",male,29,0,0,343276,8.05,,S\r\n92,0,3,"Andreasson, Mr. Paul Edvin",male,20,0,0,347466,7.8542,,S\r\n93,0,1,"Chaffee, Mr. Herbert Fuller",male,46,1,0,W.E.P. 5734,61.175,E31,S\r\n94,0,3,"Dean, Mr. Bertram Frank",male,26,1,2,C.A. 2315,20.575,,S\r\n95,0,3,"Coxon, Mr. Daniel",male,59,0,0,364500,7.25,,S\r\n96,0,3,"Shorney, Mr. Charles Joseph",male,,0,0,374910,8.05,,S\r\n97,0,1,"Goldschmidt, Mr. George B",male,71,0,0,PC 17754,34.6542,A5,C\r\n98,1,1,"Greenfield, Mr. William Bertram",male,23,0,1,PC 17759,63.3583,D10 D12,C\r\n99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34,0,1,231919,23,,S\r\n100,0,2,"Kantor, Mr. Sinai",male,34,1,0,244367,26,,S\r\n101,0,3,"Petranec, Miss. Matilda",female,28,0,0,349245,7.8958,,S\r\n102,0,3,"Petroff, Mr. Pastcho (""Pentcho"")",male,,0,0,349215,7.8958,,S\r\n103,0,1,"White, Mr. Richard Frasar",male,21,0,1,35281,77.2875,D26,S\r\n104,0,3,"Johansson, Mr. Gustaf Joel",male,33,0,0,7540,8.6542,,S\r\n105,0,3,"Gustafsson, Mr. Anders Vilhelm",male,37,2,0,3101276,7.925,,S\r\n106,0,3,"Mionoff, Mr. Stoytcho",male,28,0,0,349207,7.8958,,S\r\n107,1,3,"Salkjelsvik, Miss. Anna Kristine",female,21,0,0,343120,7.65,,S\r\n108,1,3,"Moss, Mr. Albert Johan",male,,0,0,312991,7.775,,S\r\n109,0,3,"Rekic, Mr. Tido",male,38,0,0,349249,7.8958,,S\r\n110,1,3,"Moran, Miss. Bertha",female,,1,0,371110,24.15,,Q\r\n111,0,1,"Porter, Mr. Walter Chamberlain",male,47,0,0,110465,52,C110,S\r\n112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,,C\r\n113,0,3,"Barton, Mr. David John",male,22,0,0,324669,8.05,,S\r\n114,0,3,"Jussila, Miss. Katriina",female,20,1,0,4136,9.825,,S\r\n115,0,3,"Attalah, Miss. Malake",female,17,0,0,2627,14.4583,,C\r\n116,0,3,"Pekoniemi, Mr. Edvard",male,21,0,0,STON/O 2. 3101294,7.925,,S\r\n117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.75,,Q\r\n118,0,2,"Turpin, Mr. William John Robert",male,29,1,0,11668,21,,S\r\n119,0,1,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C\r\n120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2,4,2,347082,31.275,,S\r\n121,0,2,"Hickman, Mr. Stanley George",male,21,2,0,S.O.C. 14879,73.5,,S\r\n122,0,3,"Moore, Mr. Leonard Charles",male,,0,0,A4. 54510,8.05,,S\r\n123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,,C\r\n124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13,E101,S\r\n125,0,1,"White, Mr. Percival Wayland",male,54,0,1,35281,77.2875,D26,S\r\n126,1,3,"Nicola-Yarred, Master. Elias",male,12,1,0,2651,11.2417,,C\r\n127,0,3,"McMahon, Mr. Martin",male,,0,0,370372,7.75,,Q\r\n128,1,3,"Madsen, Mr. Fridtjof Arne",male,24,0,0,C 17369,7.1417,,S\r\n129,1,3,"Peter, Miss. Anna",female,,1,1,2668,22.3583,F E69,C\r\n130,0,3,"Ekstrom, Mr. Johan",male,45,0,0,347061,6.975,,S\r\n131,0,3,"Drazenoic, Mr. Jozef",male,33,0,0,349241,7.8958,,C\r\n132,0,3,"Coelho, Mr. Domingos Fernandeo",male,20,0,0,SOTON/O.Q. 3101307,7.05,,S\r\n133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47,1,0,A/5. 3337,14.5,,S\r\n134,1,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29,1,0,228414,26,,S\r\n135,0,2,"Sobey, Mr. Samuel James Hayden",male,25,0,0,C.A. 29178,13,,S\r\n136,0,2,"Richard, Mr. Emile",male,23,0,0,SC/PARIS 2133,15.0458,,C\r\n137,1,1,"Newsom, Miss. Helen Monypeny",female,19,0,2,11752,26.2833,D47,S\r\n138,0,1,"Futrelle, Mr. Jacques Heath",male,37,1,0,113803,53.1,C123,S\r\n139,0,3,"Osen, Mr. Olaf Elon",male,16,0,0,7534,9.2167,,S\r\n140,0,1,"Giglio, Mr. Victor",male,24,0,0,PC 17593,79.2,B86,C\r\n141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,,0,2,2678,15.2458,,C\r\n142,1,3,"Nysten, Miss. Anna Sofia",female,22,0,0,347081,7.75,,S\r\n143,1,3,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)",female,24,1,0,STON/O2. 3101279,15.85,,S\r\n144,0,3,"Burke, Mr. Jeremiah",male,19,0,0,365222,6.75,,Q\r\n145,0,2,"Andrew, Mr. Edgardo Samuel",male,18,0,0,231945,11.5,,S\r\n146,0,2,"Nicholls, Mr. Joseph Charles",male,19,1,1,C.A. 33112,36.75,,S\r\n147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27,0,0,350043,7.7958,,S\r\n148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9,2,2,W./C. 6608,34.375,,S\r\n149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26,F2,S\r\n150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42,0,0,244310,13,,S\r\n151,0,2,"Bateman, Rev. Robert James",male,51,0,0,S.O.P. 1166,12.525,,S\r\n152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22,1,0,113776,66.6,C2,S\r\n153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.05,,S\r\n154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5,,S\r\n155,0,3,"Olsen, Mr. Ole Martin",male,,0,0,Fa 265302,7.3125,,S\r\n156,0,1,"Williams, Mr. Charles Duane",male,51,0,1,PC 17597,61.3792,,C\r\n157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16,0,0,35851,7.7333,,Q\r\n158,0,3,"Corn, Mr. Harry",male,30,0,0,SOTON/OQ 392090,8.05,,S\r\n159,0,3,"Smiljanic, Mr. Mile",male,,0,0,315037,8.6625,,S\r\n160,0,3,"Sage, Master. Thomas Henry",male,,8,2,CA. 2343,69.55,,S\r\n161,0,3,"Cribb, Mr. John Hatfield",male,44,0,1,371362,16.1,,S\r\n162,1,2,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Milne)",female,40,0,0,C.A. 33595,15.75,,S\r\n163,0,3,"Bengtsson, Mr. John Viktor",male,26,0,0,347068,7.775,,S\r\n164,0,3,"Calic, Mr. Jovo",male,17,0,0,315093,8.6625,,S\r\n165,0,3,"Panula, Master. Eino Viljami",male,1,4,1,3101295,39.6875,,S\r\n166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9,0,2,363291,20.525,,S\r\n167,1,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,,0,1,113505,55,E33,S\r\n168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45,1,4,347088,27.9,,S\r\n169,0,1,"Baumann, Mr. John D",male,,0,0,PC 17318,25.925,,S\r\n170,0,3,"Ling, Mr. Lee",male,28,0,0,1601,56.4958,,S\r\n171,0,1,"Van der hoef, Mr. Wyckoff",male,61,0,0,111240,33.5,B19,S\r\n172,0,3,"Rice, Master. Arthur",male,4,4,1,382652,29.125,,Q\r\n173,1,3,"Johnson, Miss. Eleanor Ileen",female,1,1,1,347742,11.1333,,S\r\n174,0,3,"Sivola, Mr. Antti Wilhelm",male,21,0,0,STON/O 2. 3101280,7.925,,S\r\n175,0,1,"Smith, Mr. James Clinch",male,56,0,0,17764,30.6958,A7,C\r\n176,0,3,"Klasen, Mr. Klas Albin",male,18,1,1,350404,7.8542,,S\r\n177,0,3,"Lefebre, Master. Henry Forbes",male,,3,1,4133,25.4667,,S\r\n178,0,1,"Isham, Miss. Ann Elizabeth",female,50,0,0,PC 17595,28.7125,C49,C\r\n179,0,2,"Hale, Mr. Reginald",male,30,0,0,250653,13,,S\r\n180,0,3,"Leonard, Mr. Lionel",male,36,0,0,LINE,0,,S\r\n181,0,3,"Sage, Miss. Constance Gladys",female,,8,2,CA. 2343,69.55,,S\r\n182,0,2,"Pernot, Mr. Rene",male,,0,0,SC/PARIS 2131,15.05,,C\r\n183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9,4,2,347077,31.3875,,S\r\n184,1,2,"Becker, Master. Richard F",male,1,2,1,230136,39,F4,S\r\n185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4,0,2,315153,22.025,,S\r\n186,0,1,"Rood, Mr. Hugh Roscoe",male,,0,0,113767,50,A32,S\r\n187,1,3,"O\'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,,1,0,370365,15.5,,Q\r\n188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45,0,0,111428,26.55,,S\r\n189,0,3,"Bourke, Mr. John",male,40,1,1,364849,15.5,,Q\r\n190,0,3,"Turcin, Mr. Stjepan",male,36,0,0,349247,7.8958,,S\r\n191,1,2,"Pinsky, Mrs. (Rosa)",female,32,0,0,234604,13,,S\r\n192,0,2,"Carbines, Mr. William",male,19,0,0,28424,13,,S\r\n193,1,3,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19,1,0,350046,7.8542,,S\r\n194,1,2,"Navratil, Master. Michel M",male,3,1,1,230080,26,F2,S\r\n195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,B4,C\r\n196,1,1,"Lurette, Miss. Elise",female,58,0,0,PC 17569,146.5208,B80,C\r\n197,0,3,"Mernagh, Mr. Robert",male,,0,0,368703,7.75,,Q\r\n198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42,0,1,4579,8.4042,,S\r\n199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,,0,0,370370,7.75,,Q\r\n200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24,0,0,248747,13,,S\r\n201,0,3,"Vande Walle, Mr. Nestor Cyriel",male,28,0,0,345770,9.5,,S\r\n202,0,3,"Sage, Mr. Frederick",male,,8,2,CA. 2343,69.55,,S\r\n203,0,3,"Johanson, Mr. Jakob Alfred",male,34,0,0,3101264,6.4958,,S\r\n204,0,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,,C\r\n205,1,3,"Cohen, Mr. Gurshon ""Gus""",male,18,0,0,A/5 3540,8.05,,S\r\n206,0,3,"Strom, Miss. Telma Matilda",female,2,0,1,347054,10.4625,G6,S\r\n207,0,3,"Backstrom, Mr. Karl Alfred",male,32,1,0,3101278,15.85,,S\r\n208,1,3,"Albimona, Mr. Nassef Cassem",male,26,0,0,2699,18.7875,,C\r\n209,1,3,"Carr, Miss. Helen ""Ellen""",female,16,0,0,367231,7.75,,Q\r\n210,1,1,"Blank, Mr. Henry",male,40,0,0,112277,31,A31,C\r\n211,0,3,"Ali, Mr. Ahmed",male,24,0,0,SOTON/O.Q. 3101311,7.05,,S\r\n212,1,2,"Cameron, Miss. Clear Annie",female,35,0,0,F.C.C. 13528,21,,S\r\n213,0,3,"Perkin, Mr. John Henry",male,22,0,0,A/5 21174,7.25,,S\r\n214,0,2,"Givard, Mr. Hans Kristensen",male,30,0,0,250646,13,,S\r\n215,0,3,"Kiernan, Mr. Philip",male,,1,0,367229,7.75,,Q\r\n216,1,1,"Newell, Miss. Madeleine",female,31,1,0,35273,113.275,D36,C\r\n217,1,3,"Honkanen, Miss. Eliina",female,27,0,0,STON/O2. 3101283,7.925,,S\r\n218,0,2,"Jacobsohn, Mr. Sidney Samuel",male,42,1,0,243847,27,,S\r\n219,1,1,"Bazzani, Miss. Albina",female,32,0,0,11813,76.2917,D15,C\r\n220,0,2,"Harris, Mr. Walter",male,30,0,0,W/C 14208,10.5,,S\r\n221,1,3,"Sunderland, Mr. Victor Francis",male,16,0,0,SOTON/OQ 392089,8.05,,S\r\n222,0,2,"Bracken, Mr. James H",male,27,0,0,220367,13,,S\r\n223,0,3,"Green, Mr. George Henry",male,51,0,0,21440,8.05,,S\r\n224,0,3,"Nenkoff, Mr. Christo",male,,0,0,349234,7.8958,,S\r\n225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38,1,0,19943,90,C93,S\r\n226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22,0,0,PP 4348,9.35,,S\r\n227,1,2,"Mellors, Mr. William John",male,19,0,0,SW/PP 751,10.5,,S\r\n228,0,3,"Lovell, Mr. John Hall (""Henry"")",male,20.5,0,0,A/5 21173,7.25,,S\r\n229,0,2,"Fahlstrom, Mr. Arne Jonas",male,18,0,0,236171,13,,S\r\n230,0,3,"Lefebre, Miss. Mathilde",female,,3,1,4133,25.4667,,S\r\n231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35,1,0,36973,83.475,C83,S\r\n232,0,3,"Larsson, Mr. Bengt Edvin",male,29,0,0,347067,7.775,,S\r\n233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59,0,0,237442,13.5,,S\r\n234,1,3,"Asplund, Miss. Lillian Gertrud",female,5,4,2,347077,31.3875,,S\r\n235,0,2,"Leyson, Mr. Robert William Norman",male,24,0,0,C.A. 29566,10.5,,S\r\n236,0,3,"Harknett, Miss. Alice Phoebe",female,,0,0,W./C. 6609,7.55,,S\r\n237,0,2,"Hold, Mr. Stephen",male,44,1,0,26707,26,,S\r\n238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8,0,2,C.A. 31921,26.25,,S\r\n239,0,2,"Pengelly, Mr. Frederick William",male,19,0,0,28665,10.5,,S\r\n240,0,2,"Hunt, Mr. George Henry",male,33,0,0,SCO/W 1585,12.275,,S\r\n241,0,3,"Zabour, Miss. Thamine",female,,1,0,2665,14.4542,,C\r\n242,1,3,"Murphy, Miss. Katherine ""Kate""",female,,1,0,367230,15.5,,Q\r\n243,0,2,"Coleridge, Mr. Reginald Charles",male,29,0,0,W./C. 14263,10.5,,S\r\n244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22,0,0,STON/O 2. 3101275,7.125,,S\r\n245,0,3,"Attalah, Mr. Sleiman",male,30,0,0,2694,7.225,,C\r\n246,0,1,"Minahan, Dr. William Edward",male,44,2,0,19928,90,C78,Q\r\n247,0,3,"Lindahl, Miss. Agda Thorilda Viktoria",female,25,0,0,347071,7.775,,S\r\n248,1,2,"Hamalainen, Mrs. William (Anna)",female,24,0,2,250649,14.5,,S\r\n249,1,1,"Beckwith, Mr. Richard Leonard",male,37,1,1,11751,52.5542,D35,S\r\n250,0,2,"Carter, Rev. Ernest Courtenay",male,54,1,0,244252,26,,S\r\n251,0,3,"Reed, Mr. James George",male,,0,0,362316,7.25,,S\r\n252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29,1,1,347054,10.4625,G6,S\r\n253,0,1,"Stead, Mr. William Thomas",male,62,0,0,113514,26.55,C87,S\r\n254,0,3,"Lobb, Mr. William Arthur",male,30,1,0,A/5. 3336,16.1,,S\r\n255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41,0,2,370129,20.2125,,S\r\n256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29,0,2,2650,15.2458,,C\r\n257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,,0,0,PC 17585,79.2,,C\r\n258,1,1,"Cherry, Miss. Gladys",female,30,0,0,110152,86.5,B77,S\r\n259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,,C\r\n260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50,0,1,230433,26,,S\r\n261,0,3,"Smith, Mr. Thomas",male,,0,0,384461,7.75,,Q\r\n262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3,4,2,347077,31.3875,,S\r\n263,0,1,"Taussig, Mr. Emil",male,52,1,1,110413,79.65,E67,S\r\n264,0,1,"Harrison, Mr. William",male,40,0,0,112059,0,B94,S\r\n265,0,3,"Henry, Miss. Delia",female,,0,0,382649,7.75,,Q\r\n266,0,2,"Reeves, Mr. David",male,36,0,0,C.A. 17248,10.5,,S\r\n267,0,3,"Panula, Mr. Ernesti Arvid",male,16,4,1,3101295,39.6875,,S\r\n268,1,3,"Persson, Mr. Ernst Ulrik",male,25,1,0,347083,7.775,,S\r\n269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58,0,1,PC 17582,153.4625,C125,S\r\n270,1,1,"Bissette, Miss. Amelia",female,35,0,0,PC 17760,135.6333,C99,S\r\n271,0,1,"Cairns, Mr. Alexander",male,,0,0,113798,31,,S\r\n272,1,3,"Tornquist, Mr. William Henry",male,25,0,0,LINE,0,,S\r\n273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41,0,1,250644,19.5,,S\r\n274,0,1,"Natsch, Mr. Charles H",male,37,0,1,PC 17596,29.7,C118,C\r\n275,1,3,"Healy, Miss. Hanora ""Nora""",female,,0,0,370375,7.75,,Q\r\n276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S\r\n277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45,0,0,347073,7.75,,S\r\n278,0,2,"Parkes, Mr. Francis ""Frank""",male,,0,0,239853,0,,S\r\n279,0,3,"Rice, Master. Eric",male,7,4,1,382652,29.125,,Q\r\n280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35,1,1,C.A. 2673,20.25,,S\r\n281,0,3,"Duane, Mr. Frank",male,65,0,0,336439,7.75,,Q\r\n282,0,3,"Olsson, Mr. Nils Johan Goransson",male,28,0,0,347464,7.8542,,S\r\n283,0,3,"de Pelsmaeker, Mr

In [ ]:
!ls

 sample_data  'train (1).csv'

# Task 1: Handling Missing Data – Titanic Dataset

## Task Overview
The objective of this task is to identify and handle missing values in the Titanic dataset.

## Techniques Used
- Median Imputation (Age)
- Mode Imputation (Embarked)
- Dropping Column (Cabin)

## Why These Techniques?
- Age is numerical → Median is robust to outliers.
- Embarked is categorical → Mode is appropriate.
- Cabin contains excessive missing values → Dropping avoids noise.

In [ ]:
import pandas as pd

df = pd.read_csv("train (1).csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [ ]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
df.drop('Cabin', axis=1, inplace=True)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Results & Observations

- Missing values were identified in Age, Cabin, and Embarked.
- Age was filled using median imputation.
- Embarked was filled using mode imputation.
- Cabin column was dropped due to excessive missing values.
- The dataset now contains no missing values and is ready for modeling.

# Task 2: Feature Encoding – Car Evaluation Dataset

## Task Overview
The objective of this task is to encode categorical variables in the Car Evaluation dataset.

## Techniques Used
- Label Encoding
- One-Hot Encoding

## Why These Techniques?
- Label Encoding converts categorical values into numeric form.
- One-Hot Encoding avoids ordinal relationships in nominal categories.
- Both techniques are compared to observe structural differences.

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data

--2026-02-26 09:56:02--  https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘car.data’

car.data                [ <=>                ]  50.65K  --.-KB/s    in 0.1s

2026-02-26 09:56:02 (516 KB/s) - ‘car.data’ saved [51867]

In [ ]:
import pandas as pd

columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

df_car = pd.read_csv("car.data", names=columns)
df_car.head()

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [ ]:
df_car.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
class       object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_label = df_car.copy()

for col in df_label.columns:
    df_label[col] = le.fit_transform(df_label[col])

df_label.head()

   buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [ ]:
df_onehot = pd.get_dummies(df_car)

df_onehot.head()

,buying_high,buying_low,buying_med,buying_vhigh,maint_high,maint_low,maint_med,maint_vhigh,doors_2,doors_3,...,lug_boot_big,lug_boot_med,lug_boot_small,safety_high,safety_low,safety_med,class_acc,class_good,class_unacc,class_vgood
0,False,False,False,True,False,False,False,True,True,False,...,False,False,True,False,True,False,False,False,True,False
1,False,False,False,True,False,False,False,True,True,False,...,False,False,True,False,False,True,False,False,True,False
2,False,False,False,True,False,False,False,True,True,False,...,False,False,True,True,False,False,False,False,True,False
3,False,False,False,True,False,False,False,True,True,False,...,False,True,False,False,True,False,False,False,True,False
4,False,False,False,True,False,False,False,True,True,False,...,False,True,False,False,False,True,False,False,True,False

In [ ]:
print("Original Shape:", df_car.shape)
print("Label Encoded Shape:", df_label.shape)
print("One-Hot Encoded Shape:", df_onehot.shape)

Original Shape: (1728, 7)
Label Encoded Shape: (1728, 7)
One-Hot Encoded Shape: (1728, 25)

## Results & Observations

- Label Encoding converted categorical values into numeric form without increasing feature count.
- One-Hot Encoding expanded the dataset by creating separate binary columns.
- One-Hot Encoding avoids unintended ordinal relationships.
- Both techniques successfully transformed categorical variables into machine learning compatible format.

# Task 3: Feature Scaling – Wine Quality Dataset

## Task Overview
The objective of this task is to apply feature scaling techniques to numerical variables in the Wine Quality dataset.

## Techniques Used
- Standardization (StandardScaler)
- Normalization (MinMaxScaler)

## Why These Techniques?
- Standardization transforms data to mean = 0 and standard deviation = 1.
- Normalization scales features to a range between 0 and 1.
- Scaling ensures better performance for distance-based and gradient-based models.

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

--2026-02-26 09:57:47--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘winequality-red.csv’

winequality-red.csv     [ <=>                ]  82.23K  --.-KB/s    in 0.1s

2026-02-26 09:57:48 (837 KB/s) - ‘winequality-red.csv’ saved [84199]

In [ ]:
import pandas as pd

df_wine = pd.read_csv("winequality-red.csv", sep=';')
df_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:

df_wine.shape

(1599, 12)

In [ ]:
X = df_wine.drop("quality", axis=1)
y = df_wine["quality"]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()
X_minmax = scaler_minmax.fit_transform(X)

X_minmax = pd.DataFrame(X_minmax, columns=X.columns)
X_minmax.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846
1,0.283186,0.520548,0.00,0.116438,0.143573,0.338028,0.215548,0.494126,0.362205,0.209581,0.215385
2,0.283186,0.438356,0.04,0.095890,0.133556,0.197183,0.169611,0.508811,0.409449,0.191617,0.215385
3,0.584071,0.109589,0.56,0.068493,0.105175,0.225352,0.190813,0.582232,0.330709,0.149701,0.215385
4,0.247788,0.397260,0.00,0.068493,0.106845,0.140845,0.098940,0.567548,0.606299,0.137725,0.153846

In [ ]:
print("Original Mean:\n", X.mean())
print("\nStandardized Mean:\n", X_standard.mean())
print("\nNormalized Min:\n", X_minmax.min())
print("\nNormalized Max:\n", X_minmax.max())

Original Mean:
 fixed acidity            8.319637
volatile acidity         0.527821
citric acid              0.270976
residual sugar           2.538806
chlorides                0.087467
free sulfur dioxide     15.874922
total sulfur dioxide    46.467792
density                  0.996747
pH                       3.311113
sulphates                0.658149
alcohol                 10.422983
dtype: float64

Standardized Mean:
 fixed acidity           3.554936e-16
volatile acidity        1.733031e-16
citric acid            -8.887339e-17
residual sugar         -1.244227e-16
chlorides               3.732682e-16
free sulfur dioxide    -6.221137e-17
total sulfur dioxide    4.443669e-17
density                -3.473172e-14
pH                      2.861723e-15
sulphates               6.754377e-16
alcohol                 1.066481e-16
dtype: float64

Normalized Min:
 fixed acidity           0.0
volatile acidity        0.0
citric acid             0.0
residual sugar          0.0
chlorides               0.0
free sulfur dioxide     0.0
total sulfur dioxide    0.0
density                 0.0
pH                      0.0
sulphates               0.0
alcohol                 0.0
dtype: float64

Normalized Max:
 fixed acidity           1.0
volatile acidity        1.0
citric acid             1.0
residual sugar          1.0
chlorides               1.0
free sulfur dioxide     1.0
total sulfur dioxide    1.0
density                 1.0
pH                      1.0
sulphates               1.0
alcohol                 1.0
dtype: float64

## Results & Observations

- Standardization transformed features to mean approximately 0 and standard deviation close to 1.
- Normalization scaled all features between 0 and 1.
- Scaling ensures that no feature dominates due to larger magnitude.
- The dataset is now suitable for machine learning algorithms requiring scaled inputs.

# Task 4: Handling Outliers – Boston Housing Dataset

## Task Overview
The objective of this task is to detect and treat outliers in the Boston Housing dataset.

## Techniques Used
- Z-Score Method
- IQR Method

## Why These Techniques?
- Z-Score identifies extreme values based on standard deviation.
- IQR method detects outliers using interquartile range.
- Removing outliers improves model stability and reduces noise.

In [ ]:
from sklearn.datasets import fetch_openml
import pandas as pd

boston = fetch_openml(name="boston", version=1, as_frame=True)
df_boston = boston.frame

df_boston.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
import numpy as np
from scipy import stats

# Sirf numerical columns select karein
df_numeric = df_boston.select_dtypes(include=[np.number])

# Z-score calculate karein
z_scores = np.abs(stats.zscore(df_numeric))

# Outliers remove karein
df_zscore = df_boston[(z_scores < 3).all(axis=1)]

print("Original Shape:", df_boston.shape)
print("After Z-Score Removal:", df_zscore.shape)

Original Shape: (506, 14)
After Z-Score Removal: (448, 14)

In [ ]:
Q1 = df_numeric.quantile(0.25)
Q3 = df_numeric.quantile(0.75)
IQR = Q3 - Q1

df_iqr = df_boston[~((df_numeric < (Q1 - 1.5 * IQR)) |
                      (df_numeric > (Q3 + 1.5 * IQR))).any(axis=1)]

print("Original Shape:", df_boston.shape)
print("After IQR Removal:", df_iqr.shape)

Original Shape: (506, 14)
After IQR Removal: (288, 14)

## Results & Observations

- Z-Score method removed data points beyond 3 standard deviations.
- IQR method removed values outside the interquartile range.
- The dataset size decreased after outlier removal.
- Removing outliers helps reduce noise and improves model stability.

# Task 5: Advanced Data Imputation – Retail Sales Dataset

## Task Overview
The objective of this task is to handle missing values using advanced imputation techniques.

## Techniques Used
- KNN Imputation
- MICE (Iterative Imputer)

## Why These Techniques?
- KNN fills missing values using nearest neighbors.
- MICE uses regression-based iterative estimation.
- Advanced imputation provides more realistic value estimation than simple mean/median.

In [ ]:
!wget https://raw.githubusercontent.com/selva86/datasets/master/RetailMarketing.csv

--2026-02-26 10:06:02--  https://raw.githubusercontent.com/selva86/datasets/master/RetailMarketing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2026-02-26 10:06:02 ERROR 404: Not Found.

In [1]:
import pandas as pd
import numpy as np

# Simple retail-like dataset
np.random.seed(42)

df_retail = pd.DataFrame({
    "Sales": np.random.randint(100, 1000, 200),
    "Customers": np.random.randint(10, 100, 200),
    "Discount": np.random.uniform(0, 0.5, 200),
    "Inventory": np.random.randint(50, 500, 200)
})

df_retail.head()

   Sales  Customers  Discount  Inventory
0    202         95  0.161275        240
1    535         37  0.424335        418
2    960         75  0.068311        458
3    370         51  0.354455        361
4    206         54  0.276410        466

In [2]:
df_retail_missing = df_retail.copy()

for col in df_retail_missing.columns:
    df_retail_missing.loc[df_retail_missing.sample(frac=0.1).index, col] = np.nan

df_retail_missing.isnull().sum()

Sales        20
Customers    20
Discount     20
Inventory    20
dtype: int64

In [3]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=5)

df_knn = pd.DataFrame(
    knn_imputer.fit_transform(df_retail_missing),
    columns=df_retail_missing.columns
)

df_knn.isnull().sum()

Sales        0
Customers    0
Discount     0
Inventory    0
dtype: int64

In [4]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

mice_imputer = IterativeImputer(random_state=42)

df_mice = pd.DataFrame(
    mice_imputer.fit_transform(df_retail_missing),
    columns=df_retail_missing.columns
)

df_mice.isnull().sum()

Sales        0
Customers    0
Discount     0
Inventory    0
dtype: int64

## Results & Observations

- Artificial missing values were introduced.
- KNN Imputer filled values using nearest neighbors.
- MICE used regression-based iterative estimation.
- Both methods successfully removed missing values.
- Advanced imputation provides more realistic estimates than simple mean or median.

# Task 6: Feature Engineering – Heart Disease Dataset

## Task Overview
The objective of this task is to create new derived features from existing variables in the Heart Disease dataset.

## Feature Engineering Applied
- Age Groups
- Cholesterol Category
- Risk Factor Count

## Why Feature Engineering?
- Derived features improve model interpretability.
- Grouping continuous variables helps capture patterns.
- Combining related features improves predictive signal.

In [7]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer(as_frame=True)
df_heart = data.frame

df_heart.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [8]:
df_heart["radius_group"] = pd.cut(
    df_heart["mean radius"],
    bins=3,
    labels=["Low", "Medium", "High"]
)

df_heart[["mean radius", "radius_group"]].head()

   mean radius radius_group
0        17.99       Medium
1        20.57       Medium
2        19.69       Medium
3        11.42          Low
4        20.29       Medium

In [9]:
df_heart["texture_category"] = pd.cut(
    df_heart["mean texture"],
    bins=3,
    labels=["Low", "Medium", "High"]
)

df_heart[["mean texture", "texture_category"]].head()

   mean texture texture_category
0         10.38              Low
1         17.77              Low
2         21.25           Medium
3         20.38           Medium
4         14.34              Low

In [10]:
df_heart["risk_score"] = (
    (df_heart["mean radius"] > df_heart["mean radius"].mean()).astype(int) +
    (df_heart["mean texture"] > df_heart["mean texture"].mean()).astype(int)
)

df_heart[["mean radius", "mean texture", "risk_score"]].head()

   mean radius  mean texture  risk_score
0        17.99         10.38           1
1        20.57         17.77           1
2        19.69         21.25           2
3        11.42         20.38           1
4        20.29         14.34           1

## Results & Observations

- Continuous variables were grouped into categories.
- Derived categorical features improve interpretability.
- A new combined risk score feature was created.
- Feature engineering enhances predictive information.

# Task 7: Variable Transformation – Bike Sharing Dataset

## Task Overview
The objective of this task is to transform skewed numerical variables to improve their distribution.

## Techniques Used
- Log Transformation
- Square Root Transformation
- Box-Cox Transformation

## Why?
Transformations reduce skewness and stabilize variance,
which improves performance of machine learning models.

In [12]:
from sklearn.datasets import load_diabetes
import pandas as pd

data = load_diabetes(as_frame=True)
df_bike = data.frame   # naam same rakh rahe hain consistency ke liye

df_bike.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [13]:
df_bike["target"].skew()

np.float64(0.44056293407014124)

In [14]:
import numpy as np

# target me negative values ho sakti hain isliye shift karenge
shift_value = abs(df_bike["target"].min()) + 1

df_bike["target_log"] = np.log1p(df_bike["target"] + shift_value)

df_bike[["target", "target_log"]].head()

   target  target_log
0   151.0    5.181784
1    75.0    4.624973
2   141.0    5.123964
3   206.0    5.451038
4   135.0    5.087596

In [15]:
df_bike["target_sqrt"] = np.sqrt(df_bike["target"] + shift_value)

df_bike[["target", "target_sqrt"]].head()

   target  target_sqrt
0   151.0    13.304135
1    75.0    10.049876
2   141.0    12.922848
3   206.0    15.231546
4   135.0    12.688578

In [16]:
from scipy import stats

df_bike["target_boxcox"], lambda_value = stats.boxcox(df_bike["target"] + shift_value)

lambda_value

np.float64(0.21056776935009533)

In [17]:
print("Original Skewness:", df_bike["target"].skew())
print("Log Skewness:", df_bike["target_log"].skew())
print("Sqrt Skewness:", df_bike["target_sqrt"].skew())
print("BoxCox Skewness:", df_bike["target_boxcox"].skew())

Original Skewness: 0.44056293407014124
Log Skewness: -0.1649048823642757
Sqrt Skewness: 0.1450393206346285
BoxCox Skewness: -0.034333089667264935

## Results & Observations

- The original variable showed skewness.
- Log and square root transformations reduced skewness.
- Box-Cox provided the most normalized distribution.
- Transformation improves feature suitability for ML models.

# Task 8: Feature Selection – Diabetes Dataset

## Task Overview
The objective of this task is to select important features using different feature selection techniques.

## Techniques Used
- Correlation Analysis
- Mutual Information
- Recursive Feature Elimination (RFE)

## Why?
Feature selection reduces dimensionality, improves model performance,
and removes irrelevant variables.

In [18]:
from sklearn.datasets import load_diabetes
import pandas as pd

data = load_diabetes(as_frame=True)
df_diabetes = data.frame

df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [19]:
X = df_diabetes.drop("target", axis=1)
y = df_diabetes["target"]

In [20]:
correlation = X.corrwith(y)
correlation.sort_values(ascending=False)

bmi    0.586450
s5     0.565883
bp     0.441482
s4     0.430453
s6     0.382483
s1     0.212022
age    0.187889
s2     0.174054
sex    0.043062
s3    -0.394789
dtype: float64

In [21]:
from sklearn.feature_selection import mutual_info_regression

mi_scores = mutual_info_regression(X, y)

mi_series = pd.Series(mi_scores, index=X.columns)
mi_series.sort_values(ascending=False)

bmi    0.176365
s5     0.148758
s4     0.106654
s6     0.090785
s1     0.065230
s3     0.062773
bp     0.061967
sex    0.026064
s2     0.010072
age    0.000000
dtype: float64

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

model = LinearRegression()
rfe = RFE(model, n_features_to_select=5)

rfe.fit(X, y)

selected_features = X.columns[rfe.support_]
selected_features

Index(['bmi', 'bp', 's1', 's2', 's5'], dtype='object')

## Results & Observations

- Correlation analysis identified strongly related features.
- Mutual information measured dependency between variables.
- RFE selected the top 5 most important features.
- Feature selection reduces dimensionality and improves model efficiency.

# Task 9: Handling Imbalanced Data – Credit Card Fraud

## Task Overview
The objective of this task is to handle class imbalance in a dataset.

## Techniques Used
- Random Undersampling
- SMOTE
- ADASYN

## Why?
Imbalanced datasets bias models toward majority class.
Balancing improves minority class prediction.

In [23]:
from sklearn.datasets import make_classification
import pandas as pd

X, y = make_classification(
    n_samples=5000,
    n_features=10,
    n_classes=2,
    weights=[0.95, 0.05],   # 95% majority, 5% minority
    random_state=42
)

df_imb = pd.DataFrame(X)
df_imb["target"] = y

df_imb["target"].value_counts()

target
0    4722
1     278
Name: count, dtype: int64

In [24]:
X = df_imb.drop("target", axis=1)
y = df_imb["target"]

In [25]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42)
X_under, y_under = rus.fit_resample(X, y)

pd.Series(y_under).value_counts()

target
0    278
1    278
Name: count, dtype: int64

In [26]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)

pd.Series(y_smote).value_counts()

target
0    4722
1    4722
Name: count, dtype: int64

In [27]:
from imblearn.over_sampling import ADASYN

adasyn = ADASYN(random_state=42)
X_ada, y_ada = adasyn.fit_resample(X, y)

pd.Series(y_ada).value_counts()

target
1    4749
0    4722
Name: count, dtype: int64

## Results & Observations

- Original dataset was highly imbalanced.
- Random undersampling reduced majority class size.
- SMOTE generated synthetic minority samples.
- ADASYN adaptively generated minority samples.
- Balanced datasets improve fairness and predictive performance.

# Task 10: Combining Multiple Datasets – MovieLens

## Task Overview
The objective of this task is to merge multiple related datasets into a single structured dataset.

## Datasets Used
- Ratings
- Movies
- Users

## Why?
Combining datasets creates a unified structure for machine learning models.

In [29]:
import pandas as pd

# Ratings dataset
ratings = pd.DataFrame({
    "userId": [1,2,3,1,2],
    "movieId": [10,20,10,30,30],
    "rating": [4,5,3,2,4]
})

# Movies dataset
movies = pd.DataFrame({
    "movieId": [10,20,30],
    "title": ["Movie A","Movie B","Movie C"],
    "genre": ["Action","Comedy","Drama"]
})

# Users dataset
users = pd.DataFrame({
    "userId": [1,2,3],
    "age": [25,30,22],
    "gender": ["M","F","M"]
})

# Merge ratings & movies
df_merge1 = pd.merge(ratings, movies, on="movieId", how="inner")

# Merge with users
df_final = pd.merge(df_merge1, users, on="userId", how="inner")

df_final

   userId  movieId  rating    title   genre  age gender
0       1       10       4  Movie A  Action   25      M
1       2       20       5  Movie B  Comedy   30      F
2       3       10       3  Movie A  Action   22      M
3       1       30       2  Movie C   Drama   25      M
4       2       30       4  Movie C   Drama   30      F

## Results & Observations

- Ratings, movies, and users datasets were successfully merged.
- The final dataset contains user details, movie information, and ratings.
- Merging created a unified structured dataset.
- Combined dataset is ready for machine learning or recommendation systems.

# Task 11: Dimensionality Reduction – MNIST Dataset

## Task Overview
The objective of this task is to reduce feature space while preserving important variance.

## Techniques Used
- Principal Component Analysis (PCA)
- t-Distributed Stochastic Neighbor Embedding (t-SNE)

## Why?
Dimensionality reduction reduces computational cost,
removes redundancy, and improves visualization.

In [30]:
from sklearn.datasets import load_digits
import pandas as pd

digits = load_digits()
X = digits.data
y = digits.target

X.shape

(1797, 64)

In [31]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
X_pca = pca.fit_transform(X)

print("Original Shape:", X.shape)
print("After PCA Shape:", X_pca.shape)

Original Shape: (1797, 64)
After PCA Shape: (1797, 10)

In [32]:
pca.explained_variance_ratio_

array([0.14890594, 0.13618771, 0.11794594, 0.08409979, 0.05782415,
       0.0491691 , 0.04315987, 0.03661373, 0.03353248, 0.03078806])

In [33]:
from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X)

print("After t-SNE Shape:", X_tsne.shape)

After t-SNE Shape: (1797, 2)

## Results & Observations

- PCA reduced dimensionality from 64 to 10 components.
- PCA preserved major variance in the dataset.
- t-SNE reduced features to 2 dimensions.
- Dimensionality reduction improves computational efficiency.

# Task 12: Text Preprocessing – IMDB Reviews

## Task Overview
The objective of this task is to clean and preprocess text data for machine learning models.

## Steps Applied
- Lowercasing
- Stopword Removal
- Tokenization
- Lemmatization

## Why?
Text preprocessing removes noise and converts raw text into structured format suitable for ML models.

In [34]:
import pandas as pd

df_text = pd.DataFrame({
    "review": [
        "This movie was absolutely amazing and wonderful!",
        "The film was boring and too long.",
        "Excellent acting but the story was weak.",
        "I did not like this movie at all."
    ]
})

df_text

                                             review
0  This movie was absolutely amazing and wonderful!
1                 The film was boring and too long.
2          Excellent acting but the story was weak.
3                 I did not like this movie at all.

In [35]:
df_text["review"] = df_text["review"].str.lower()
df_text

                                             review
0  this movie was absolutely amazing and wonderful!
1                 the film was boring and too long.
2          excellent acting but the story was weak.
3                 i did not like this movie at all.

In [36]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [37]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [39]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [40]:
from nltk.tokenize import word_tokenize

df_text["tokens"] = df_text["review"].apply(word_tokenize)

df_text

,review,tokens
0,this movie was absolutely amazing and wonderful!,"[this, movie, was, absolutely, amazing, and, w..."
1,the film was boring and too long.,"[the, film, was, boring, and, too, long, .]"
2,excellent acting but the story was weak.,"[excellent, acting, but, the, story, was, weak..."
3,i did not like this movie at all.,"[i, did, not, like, this, movie, at, all, .]"

In [41]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

df_text["tokens"] = df_text["tokens"].apply(
    lambda x: [word for word in x if word not in stop_words]
)

df_text

,review,tokens
0,this movie was absolutely amazing and wonderful!,"[movie, absolutely, amazing, wonderful, !]"
1,the film was boring and too long.,"[film, boring, long, .]"
2,excellent acting but the story was weak.,"[excellent, acting, story, weak, .]"
3,i did not like this movie at all.,"[like, movie, .]"

In [42]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

df_text["tokens"] = df_text["tokens"].apply(
    lambda x: [lemmatizer.lemmatize(word) for word in x]
)

df_text

,review,tokens
0,this movie was absolutely amazing and wonderful!,"[movie, absolutely, amazing, wonderful, !]"
1,the film was boring and too long.,"[film, boring, long, .]"
2,excellent acting but the story was weak.,"[excellent, acting, story, weak, .]"
3,i did not like this movie at all.,"[like, movie, .]"

## Results & Observations

- Text was converted to lowercase.
- Reviews were tokenized into individual words.
- Stopwords were removed to eliminate noise.
- Lemmatization converted words into their base form.
- Cleaned text is ready for machine learning models.

# Task 13: Time-Series Preprocessing – Air Quality Dataset

## Task Overview
The objective of this task is to preprocess time-series data by handling timestamps and smoothing.

## Steps Applied
- Datetime conversion
- Resampling
- Handling missing values
- Rolling mean smoothing

## Why?
Time-series preprocessing ensures consistent time intervals,
reduces noise, and improves modeling performance.

In [43]:
import pandas as pd
import numpy as np

# Create hourly datetime range
date_range = pd.date_range(start="2023-01-01", periods=200, freq="H")

df_air = pd.DataFrame({
    "datetime": date_range,
    "PM2.5": np.random.normal(50, 10, 200)
})

# Introduce missing values
df_air.loc[df_air.sample(frac=0.1).index, "PM2.5"] = np.nan

df_air.head()

/tmp/ipython-input-251/2125276205.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  date_range = pd.date_range(start="2023-01-01", periods=200, freq="H")

             datetime      PM2.5
0 2023-01-01 00:00:00  49.547457
1 2023-01-01 01:00:00  37.668987
2 2023-01-01 02:00:00  63.909724
3 2023-01-01 03:00:00  36.440297
4 2023-01-01 04:00:00  48.042147

In [44]:
df_air["datetime"] = pd.to_datetime(df_air["datetime"])
df_air.set_index("datetime", inplace=True)

df_air.head()

                         PM2.5
datetime
2023-01-01 00:00:00  49.547457
2023-01-01 01:00:00  37.668987
2023-01-01 02:00:00  63.909724
2023-01-01 03:00:00  36.440297
2023-01-01 04:00:00  48.042147

In [45]:
df_air["PM2.5"] = df_air["PM2.5"].interpolate()

df_air.isnull().sum()

PM2.5    0
dtype: int64

In [46]:
df_daily = df_air.resample("D").mean()

df_daily.head()

                PM2.5
datetime
2023-01-01  48.647632
2023-01-02  52.461592
2023-01-03  51.208667
2023-01-04  46.528289
2023-01-05  45.803986

In [47]:
df_air["PM2.5_smooth"] = df_air["PM2.5"].rolling(window=5).mean()

df_air.head()

                         PM2.5  PM2.5_smooth
datetime
2023-01-01 00:00:00  49.547457           NaN
2023-01-01 01:00:00  37.668987           NaN
2023-01-01 02:00:00  63.909724           NaN
2023-01-01 03:00:00  36.440297           NaN
2023-01-01 04:00:00  48.042147     47.121722

## Results & Observations

- Datetime column was converted and set as index.
- Missing values were handled using interpolation.
- Data was resampled to daily averages.
- Rolling mean smoothing reduced short-term fluctuations.
- Time-series data is now structured and ready for forecasting models.